// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const windowBox: string;
export const languageSelection: string;
export const content: string;
