name: Intelligent Issue Resolver

on:
  issues:
    types: [opened]

jobs:
  resolve:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number}}
          comment: Code your own shit, and stop requesting.
